apiVersion: v1
kind: Service
metadata:
  name: llm-backend-service
  namespace: {{.Values.namespace}}
spec:
  selector:
    app: llm
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
