apiVersion: apps/v1
kind: Deployment
metadata:
  name: swagger-ui
  namespace: llm-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swagger-ui
  template:
    metadata:
      labels:
        app: swagger-ui
    spec:
      containers:
      - name: swagger-ui
        image: swaggerapi/swagger-ui
        ports:
        - containerPort: 8080
        env:
        - name: SWAGGER_JSON
          value: /swagger/swagger.yaml
        volumeMounts:
        - name: swagger-config
          mountPath: /swagger
          readOnly: true
      volumes:
      - name: swagger-config
        configMap:
          name: swagger-config
