apiVersion: v1
kind: Service
metadata:
  name: llm-frontend-service
  namespace: llm-namespace
spec:
  selector:
    app: swagger-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
